import "~/styles/globals.css";

import type { Metadata } from "next";
import { Comic_Neue, DynaPuff, Geist, New_Rocker } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { Sidebar } from "../components/ui/sidebar";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	display: "swap",
});

const comicNeue = Comic_Neue({
	subsets: ["latin"],
	display: "swap",
	weight: ["300", "400", "700"],
});

const dynaPuff = DynaPuff({
	subsets: ["latin"],
	display: "swap",
	weight: ["400", "700", "500", "600"],
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${dynaPuff.className} dark`}>
			<body>
				<TRPCReactProvider>
					<div className="flex min-h-screen bg-linear-to-b from-slate-900 to-slate-950">
						<Sidebar />
						<main className="mt-15 ml-15 flex-1">{children}</main>
					</div>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
