import "~/styles/globals.css";

import type { Metadata } from "next";
import { Comic_Neue, Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { Sidebar } from "../components/ui/sidebar";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

const comicRelief = Comic_Neue({
	subsets: ["latin"],
	weight: ["300", "400", "700"],
	variable: "--font-comic-relief",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${comicRelief.variable}`}>
			<body>
				<TRPCReactProvider>
					<div className="flex h-screen">
						<Sidebar />
						<main className="mt-15 ml-15 flex-1 overflow-auto">{children}</main>
					</div>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
